name: Deploy to Render

on:
  push:
    branches:
      - main  # Apenas dispara o workflow quando há um push na branch "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Versão do Python

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      # Passo 4: Testar o código (opcional)
      - name: Run tests
        run: |
          poetry run pytest

      # Passo 5: Fazer o deploy para o Render
      - name: Deploy to Render
        run: |
          echo "Fazendo deploy para o Render..."
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": true}' \
            https://api.render.com/v1/services/$SERVICE_ID/deploys